version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sciserv-app
    ports:
      - "81:80"   # แก้ตามต้องการ (เช่น 80:80 ถ้าใช้ Coolify ให้แค่ expose)
    volumes:
      - .:/var/www/html
      - laravel_storage:/var/www/html/storage
      - laravel_cache:/var/www/html/bootstrap/cache
    command: >
      sh -c "chown -R www-data:www-data /var/www && php artisan config:cache && apache2-foreground"


    depends_on:
      - db
    environment:
      DB_CONNECTION: mysql
      DB_HOST: sckw00okc0kcs8soo4c4484s
      DB_PORT: 3306
      DB_DATABASE: tss
      DB_USERNAME: mysql
      DB_PASSWORD: 7CI0ZJVNPU6hyiVP6X13iclUaQVwjIJhxetqivEtZienF7xVtNQ6ycIBWQX1Jqei

  db:
    image: mysql:8
    container_name: sciserv-db
    restart: always
    ports:
      - "3308:3306"  # แก้ตามต้องการ
    environment:
      MYSQL_DATABASE: tss
      MYSQL_ROOT_PASSWORD: Ly1Re7rVjlHKrJQjaUWHlWVE4bhadcO2mdmBi1uxL7YgDW1T40R8jH4vOgTQxVwr
      MYSQL_USER: mysql
      MYSQL_PASSWORD: 7CI0ZJVNPU6hyiVP6X13iclUaQVwjIJhxetqivEtZienF7xVtNQ6ycIBWQX1Jqei
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
  laravel_storage:
  laravel_cache:
