version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sciserv-app
    ports:
      - "80:80"   # แก้ตามต้องการ (เช่น 80:80 ถ้าใช้ Coolify ให้แค่ expose)
    volumes:
      - .:/var/www/html
      - laravel_storage:/var/www/html/storage
      - laravel_cache:/var/www/html/bootstrap/cache
    command: |
      sh -c "chown -R www-data:www-data /var/www && php artisan config:cache && php-fpm"
    depends_on:
      - db
    environment:
      DB_CONNECTION: mysql
      DB_HOST: n8c8wg880oww4scs4kggsgwk
      DB_PORT: 3306
      DB_DATABASE: tss
      DB_USERNAME: mysql
      DB_PASSWORD: 7PuQw5tKSgc8dYvBypIgH3P1690HQjckShRNtkFQMyPhdKzKzaYPbnXDpmr3wXvT

  db:
    image: mysql:8.0
    container_name: sciserv-db
    restart: always
    ports:
      - "3307:3306"  # แก้ตามต้องการ
    environment:
      MYSQL_DATABASE: tss
      MYSQL_ROOT_PASSWORD: 0zooLSIYSF5rfdyV6Sb1MGbLMXmorkqpH48LNiGWmDi496pLLW232FcWsw1alPb8
      MYSQL_USER: mysql
      MYSQL_PASSWORD: 7PuQw5tKSgc8dYvBypIgH3P1690HQjckShRNtkFQMyPhdKzKzaYPbnXDpmr3wXvT
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
  laravel_storage:
  laravel_cache:
